Add case insenstive to both table and schema search
datajoint/datajoint-labbook pull request #102
Opened 2021-03-01 19:38 UTC by Synicix

2021-03-01 20:42 UTC, mahos submitted a review, later dismissed

2021-03-02 15:07 UTC, guzman-raphael requested changes
@Synicix Make sure to update Milestone/Project appropriately.

2021-03-02 15:07 UTC, guzman-raphael commented on CHANGELOG.md
> +- Case invariate behavior to schema and table search box (#99) PR #102
Did you mean:

```suggestion
- Case insensitive behavior to schema and table search box (#99) PR #102
```

2021-03-03 13:24 UTC, guzman-raphael approved these changes

2021-03-03 13:25 UTC, guzman-raphael approved these changes
@Synicix Updated the Milestone/Project assignment for you...

2021-03-03 13:25 UTC, merged