Datetime bug with dealing with undefined values
datajoint/datajoint-labbook pull request #106
Opened 2021-03-01 22:03 UTC by Synicix

- This is bug I found with the IBL tables. It has to do with the rewrite so I didn't push a change log.

2021-03-01 22:05 UTC, Synicix commented
Can we cram this in the Beta.1? @guzman-raphael

2021-03-01 23:40 UTC, Synicix commented
I patch it temporarly for now, but yeah we really need to consildate on undefined for current value for tableAttribute

2021-03-03 22:17 UTC, Synicix commented
Update from dev now

2021-03-05 12:30 UTC, guzman-raphael requested changes
@Synicix Now that we have released in `BETA`, we will need to add a changelog entry for this bug fix. It is unclear exactly the use case where `currentValue` comes in as an array.

Please update the following:
- Changelog entry
- PR description of the actual bug
- Screenshot of the issue/fix
- Update GH Milestone/Project assignment

2021-03-05 19:57 UTC, Synicix commented
I was hopping to shove it in beta cause it was broken due to the overall to allow copy over to work the other day.

2021-03-06 21:33 UTC, mahos approved these changes

2021-03-08 14:26 UTC, guzman-raphael requested changes
@Synicix Also update the PR description. It was not clear what this PR fixes until I checked the linked issue.

2021-03-08 14:26 UTC, guzman-raphael commented on CHANGELOG.md
> +- Fixed issue website crashing when opening generate an input html block for datetime (#104) PR #106
```suggestion
- Fixed issue where website crashes when opening a filter card for datetime. (#104) PR #106
```

2021-03-08 15:53 UTC, guzman-raphael approved these changes

2021-03-08 15:53 UTC, merged