Make layout smaller screen size friendly
datajoint/datajoint-labbook pull request #127
Opened 2021-03-15 15:38 UTC by mahos

Make column size fit either the header or the body content - whichever is larger and also make the columns resizable.
fixes #11 
![resize column 1](https://user-images.githubusercontent.com/6288829/111179840-70ce3a80-857a-11eb-8e07-10f0a9bcd9bb.gif)

Make layout change for smaller screens (still in works)
fixes #58
![resize screen 1](https://user-images.githubusercontent.com/6288829/111179244-dd950500-8579-11eb-8a80-a73e9417e0b4.gif)

2021-03-16 14:26 UTC, guzman-raphael requested changes

2021-03-16 14:26 UTC, guzman-raphael commented on src/Components/MainTableView/TableContent.tsx
> +    // this.bodyColumnSizeRef = React.createRef();
Lingering debug comment.

2021-03-16 14:26 UTC, guzman-raphael commented on src/Components/MainTableView/TableContent.tsx
> +    // let headerColumns = this.headerColumnSizeRef.current.cells
Lingering debug comment.

2021-03-16 14:26 UTC, guzman-raphael commented on src/Components/MainTableView/TableContent.tsx
> +        // console.log(`Avg: ${colAvg}...Max: ${colMax}`)
Lingering debug comments.

2021-03-16 14:27 UTC, guzman-raphael commented
@mahos Would you also assign this PR to a Milestone?

2021-03-16 14:57 UTC, mahos commented on src/Components/MainTableView/TableContent.tsx
> +    // this.bodyColumnSizeRef = React.createRef();
addressed

2021-03-16 14:57 UTC, mahos commented on src/Components/MainTableView/TableContent.tsx
> +    // let headerColumns = this.headerColumnSizeRef.current.cells
addressed

2021-03-16 14:57 UTC, mahos commented on src/Components/MainTableView/TableContent.tsx
> +        // console.log(`Avg: ${colAvg}...Max: ${colMax}`)
addressed

2021-03-16 16:22 UTC, guzman-raphael submitted a review, later dismissed
@mahos Good from my side. Will give @Synicix an opportunity to give a last look and go ahead with merge.

2021-03-17 07:52 UTC, Synicix requested changes
Just one syntax change

2021-03-17 17:02 UTC, mahos commented on src/Components/MainTableView/TableContent.tsx
> +import React, { RefObject } from 'react';
yes - good catch - it's the auto import that puts those spaces by default...-_-

2021-03-17 19:05 UTC, Synicix approved these changes

2021-03-17 19:06 UTC, merged