Css rewrite
datajoint/datajoint-labbook pull request #142
Opened 2021-03-31 23:46 UTC by Synicix

- Partial rewrite of some CSS to fix odd behavior with scaling and displaysing elements. Also fix serval scrolling issues with elements

2021-04-26 23:27 UTC, Synicix commented
Requesting review on this due to Safari complaints

2021-05-27 19:34 UTC, Synicix commented
@mahos Can I get a review on this, would like to release these fixes at some point.

2021-05-27 21:12 UTC, mahos commented
> @mahos Can I get a review on this, would like to release these fixes at some point.

Hey @Synicix sorry about the delay - just checked it out and I'm still having trouble scrolling down on safari for larger tables - not sure if you intended to fix that issue here though, so let me know if I should just approve it, and we work on fixing that safari scroll issue for large tables later on.

2021-05-28 00:34 UTC, mahos approved these changes

2021-06-02 13:53 UTC, guzman-raphael requested changes
@Synicix Can you also add some POW stills/GIF's to the PR description for this fix?

2021-06-02 13:53 UTC, guzman-raphael commented on src/Components/MainTableView/TableContent.css
> +  box-sizing: border-box;
```suggestion
  box-sizing: border-box;
```

2021-06-02 23:08 UTC, Synicix commented
@guzman-raphael Added pictures

2021-06-03 16:47 UTC, guzman-raphael commented
@Synicix thanks. Is this one now ready to go? I think mentioning patching another bug but it would be in another PR?

2021-06-03 18:40 UTC, Synicix commented
Yeah, anything that is extra will be on a different PR

2021-06-07 15:42 UTC, merged